#!/usr/bin/env python3
"""
This script will be called to grade your solution.

The autograder expects this script to:
1. Read in ciphertext as first command line argument.
2. Read in a has_breakpoint flag ("true" or "false") as the second command line
   argument.
3. Print the best guess for the plaintext to stdout.

Example usage:
    ./decode-cli "$(cat data/test/ciphertext.txt)" false
    ./decode-cli "$(cat data/test/ciphertext_breakpoint.txt)" true

A default implementation calling decode.py has been provided below.
"""

import sys
import time
from src.decode import decode

has_breakpoint = sys.argv[2].lower() == "true"
debug = False
start = time.time()
print(decode(sys.argv[1], has_breakpoint, debug=debug))
if debug:
    print(time.time() - start)
